### ISSUE TITLE
Consider supporting Markdown-ish markup

### ISSUE THREAD

**Issue by salas-wcd** [meteor-gazelle/meteor-gazelle#106]
BBcode used to be THE markup but it is acctually boring to write.
We can give the possibility to write some markdown and then extends the markup like phacility did for remarkup (https://secure.phabricator.com/book/phabricator/article/remarkup/)

**Comment by ghost** [comment]
We will have to support bbcode because any site migrating to meteor-gazelle will have bbcode. What we can do however is provide packages for bbcode and markdown.

**Comment by salas-wcd** [comment]
Yes was more support two markup, so old post will still display but new one can use markdown. My bad with formulation, en is not my mother tongue :)

**Comment by c-p-b** [comment]
Supporting both is a possibility, but due to the complexity of parsing if we do add Markdown support you will likely not be able to mix the two, you will have to pick either one of the other for your post.

**Comment by salas-wcd** [comment]
> Supporting both is a possibility, but due to the complexity of parsing if we do add Markdown support you will likely not be able to mix the two, you will have to pick either one of the other for your post.

Yes seems reasonable, moreover I can carry on this task once the time comes.

**Comment by c-p-b** [comment]
Reopening this as it is an oft-requested feature and should go on the roadmap somewhere.

We will consider recommendations extending current libraries but right now I'm leaning towards [Marked](https://github.com/chjj/marked) as its BBCode variant [bboxed](https://github.com/ackwell/bboxed) is what we have built our new Javascript BBCode parser on.

**Comment by ghost** [comment]
I'd be putting a "roadmap" marker on this. It really isn't critical to what meteor-gazelle is at this stage, but it's definitely a nice to have.

**Comment by aarocka** [comment]
It should be very easy to deal with multiple markup languages. What we have to do is make sure that the database keeps track of which markup language is being used in each text posting. If you were migrating from gazelle you can safely assume that people are using BBCode. Say we had a package that parses BBCode and another one that parses Markdown. We could have a main parser that decides what parsing package corresponds to each markup language.

**Comment by ghost** [comment]
Although I agree with you @rainbowdash, I definitely think it's best to focus on other features until we are able to focus on 'nice to haves'. We need to ensure that we don't get into feature creep territory and need to focus on shippables at the moment.

**Comment by aarocka** [comment]
@belairWCD I agree, we have better things to be working on. But if we are going to implement markdown parsing down the road (or any other syntax), anything involving users and posting text needs to tell the database what kind of markup it's using. I just want to avoid the scenario where in order to implement this feature down the road we would have to rewrite a bunch of modules. But you are right, from personal experience, feature creep is very bad and we need to avoid it.

**Comment by ivoviz** [comment]
Since there will be a migration to MongoDB why not just convert the comments as well?

**Comment by ghost** [comment]
@ivoviz We don't want want to get rid of bbcode. The majority of users don't know how to use markdown but they know bbcode.

**Comment by thomwiggers** [comment]
I think that's actually shifting by now, since the popularity of reddit etc. Markdown is also easier to learn, imo, than the weak SGML (HTML) knockoff that's bbcode -- which is also poorly standardised. (See the different types of [img] tag: we support two versions.)

I think we don't need a BBCode parser to convert posts that were originally BBcode: it could be possible to import them as rendered HTML and mark them as 'imported', and have 'imported' posts bypass the parser and html escaping.

(you would need to **first** escape any existing html code **before** parsing the BBCode)

I think Markdown also works a lot better for wikis.
