### ISSUE TITLE
Consider using flexbox

### ISSUE THREAD

**Issue by salas-wcd** [meteor-gazelle/meteor-gazelle#125]
I think it's a tradeoff to evaluate:
- way nicer to use
- supports on windows and old android browser is meh ...
- native (IOS, android) are often base on this

Some links : http://s-grid.meteor.com/ for instance a grid system using flexbox

**Comment by ghost** [comment]
@salas-wcd http://neat.bourbon.io/

We're already using Bourbon so using Neat would be the natural choice. 

@sneakysneakysneaky @Malvar Care to weigh in being the css gurus?

**Comment by sneakysneakysneaky** [comment]
As ajax said, we are using [Neat](http://neat.bourbon.io/) for scaffolding, which relies on traditional floats. This will be fine for the majority of scenarios.

Nothing against flexboxes, though. I have used a few in the header for some places where floats just won't get the job done. (See [layout.scss](meteor-gazelle/packages/meteor-gazelle-theme/stylesheets/_layout.scss))

However, for stylesheets, we would like to rely on SASS libraries over Meteor packages as much as possible. Since the site will be theme-able, the developers would like to retain 100% control over the stylesheets & markup to avoid incorrect semantics & auto-generated code spaghetti. We like the [Bourbon](http://bourbon.io/) family for this reason, because it doesn't force favor any specific markup or class names.
