### ISSUE TITLE
Elastic Search

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#144]
Some of our data needs to be searchable through Elastic search. Some example are the torrents, site log, requests, user logs, artists, etc. 

This issue is to research and implement elastic search with a simple use case.

These are two packages
https://github.com/meteorbigdata/elasticsearch
https://github.com/matteodem/meteor-easy-search

The latter package supports searching either mongodb or elastic search, sounds nice but may have trade offs, something to consider.

**Comment by jimrollenhagen** [comment]
Really, the issue is that search needs to be fast as heck, right? We shouldn't artificially limit ourselves to elasticsearch, or choose it before looking at other solutions.

Mongo has some form of full-text search, as I understand it. So maybe let's roll with that for now, benchmark it when it has lots of data, and go from there to see if we need something faster?

**Comment by ghost** [comment]
@jimrollenhagen Sounds good to me. In this case I suggest we look more closely at the meteor easy search package as it does Mongo search.

**Comment by salas-wcd** [comment]
How powerful is mongo full-text search? The good think with lucene based index (like solr or elasticsearch)  is the configuration and the different filter. For example,  the possibility of synonym filter or elision filter.
