### ISSUE TITLE
Tagging system

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#150]
I've mentioned a tagging system in several comments lately, opening an issue in its honor.

A lot of content on the site carries some sort of tag, or a series of tags. I'm envisioning a single tagging system which can be adapted to different needs. Below are some examples of different uses of tags and where they appear. 
1. Simple tagging, unlimited number of tags. Appears on groups, content creators, collages, requests, wiki. 
2. Hierarchal tagging, in other words sub tags. Appears on forum threads. 

There should be a variety of options on how tags work on their respective entities. For example should the number of tags be limited, are tags restricted to a certain set, etc.

Thoughts?

**Comment by TheDevKing** [comment]
I think this is another one of those things that goes back to #137 needing to be solved first before getting too specific on this.

I think there's a case to be made that "tags", in some areas, should be done away with in favor of more content-specific descriptions, like [genre](http://schema.org/genre). It would be interesting if they could be implemented hierarchically (e.g., [music](https://en.wikipedia.org/wiki/List_of_electronic_music_genres), [books](https://en.wikipedia.org/wiki/List_of_writing_genres#Genres_and_subgenres), [film](https://en.wikipedia.org/wiki/List_of_genres#Film_and_television_genres) ).

I see hierarchy being advantageous for genres specifically to be able to easily broaden or narrow the scope of your search. For example, if you were browsing the genre "Slapstick", only things defined as "Slapstick" would show up. If you were to "go up" a level from that, you'd broaden the scope to include other forms of comedy as well. This could also be done by explicitly listing the subgenre and all parent genres as well, but to me this seems inelegant and unideal.

For genre, there would definitely have to be restrictions on what's allowed. This isn't to say they should be absolutely immutable, but enough restriction so that there's not silly things like having multiple ways of describing the exact same (sub)genre. For example, not having "drum and bass", "dnb", "drum & bass", etc.

Some interesting properties that would extend functionality and further eliminate the need for general tags include [isPartOf](http://schema.org/isPartOf), [award](http://schema.org/award), [inLanguage](http://schema.org/inLanguage), and [mentions](http://schema.org/mentions), but again, this gets back to the issue I mentioned above.

Anyway, just some food for thought.

**Comment by ghost** [comment]
@ajax-wcd just as a note, I didn't see anything in the initial specs about the labels/tags being related (for thread tagging), but I'd imagine they would be.

**Comment by ghost** [comment]
Going to start specing this out today.

**Comment by jimrollenhagen** [comment]
A few thoughts, code-wise...
- I feel like this could be a behavior in astronomy, that just adds the field or whatever is needed on the model to implement this. Methods like addTags, removeTags, etc.
- We'll need an (optional?) data model that can handle normalizing (and maybe blacklisting?) certain tags, e.g. the 'dnb' example above. Perhaps the model can be tagged with "normalize tags" or whatever. Could again be a behavior?
- Do we want to allow up/down votes on tags, like what.cd currently does for genre tags? How is that implemented?
- Hierarchical tagging seems hard and scary :) Maybe tags can be tagged? How critical is this? Doesn't seem massively useful to me, but if it's a thing people have asked for... sure.

**Comment by ghost** [comment]
@jimrollenhagen @guitarman0831 
- Agree on the Astronomy but it may be potentially useful to expose a TagManager object or something along these lines.
- Didn't think about blacklisting, very good point.
- We should support this as an optional parameter. 
- Could be scary...will need to be extra careful in the implementation. This actually isn't for tagging torrent content (although it would be beneficial) but it is tagging other content on the site such as forum threads or entries in the user's log.
