### ISSUE TITLE
Search parsing package

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#152]
A package that can be attached to a form to handle things such as negation (!query), and building the search query based on the collection and fields.

Any input?

**Comment by c-p-b** [comment]
I have used [Typeahead/Bloodhound](https://github.com/sergeyt/meteor-typeahead/) from Twitter for this in the past. It works pretty well, although as a caveat I will add all of my experience using it in the past has been with smaller databases (<500,000 records). I am not sure how well it would scale with Mongo and our schema, but if there is anyone who knows how to overcome scaling issues, it is probably Twitter. 

Whatever we should decide should be swappable later after our schema is in place so that we can test different engines with our data query plans. Once we get into doing queries on the entire Gazelle DB the scaling may make us decide one parser over the other. PHP Gazelle has the issue of not being able to autocomplete all torrents (but can do Artists, etc). Perhaps with our new schema we will be able to overcome this.

**Comment by TheDevKing** [comment]
What would be absolutely amazing is PCRE search, but I doubt that's something that could be implemented in a scalable way and would have to include negative lookahead to support negation.

**Comment by salas-wcd** [comment]
@TheDevKing This exist for lucene based search like elastic search, solr or  database that implement lucene index (neo4j, orientdb ect)

See elasticsearch about it https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-regexp-query.html

**Comment by thomwiggers** [comment]
Isn't this related to #144

**Comment by salas-wcd** [comment]
@thomwiggers it is. My answer is more about saying that it is possible and scalable.

**Comment by thomwiggers** [comment]
I meant the issue in general, not just your comment.

**Comment by ghost** [comment]
@thomwiggers Yeah. Closed that issue. This one is more relevant. 

@guitarman0831 

Research can start here 

https://github.com/matteodem/meteor-easy-search
http://mistic100.github.io/jQuery-QueryBuilder/
