### ISSUE TITLE
What about setting up a demo deployement

### ISSUE THREAD

**Issue by salas-wcd** [meteor-gazelle/meteor-gazelle#155]
Surely very low priority but also easy to fix.
Meteor allow us deploying a demo of our site into https://what-a-gorgeous-app-name.metor.com

As pro I can see that some user with low tech skill can test early and give us early concerns (about UX design, ect)

As cons, it may be useless now and i'm not aware if it is a privacy concern for us to upload in meteor.

What do you think ?

**Comment by ghost** [comment]
I don't think this is necessary. It's super easy to get meteor setup locally or on a VM. And the obvious privacy/legal concerns.

**Comment by thomwiggers** [comment]
I don't think using meteor.com will work in the long run either, because we're probably going to need stuff like ElasticSearch sooner or later, and I don't know if Meteor hosts that.

I'm in favour of self-hosting a test deployment somewhere though further down the road, to figure out deployment issues etc as well. We could set up a linux ISO tracker I suppose.

**Comment by ghost** [comment]
Hosting on meteor is a definite no.

We will self host a test deployment when the time calls for a multi user testing environment. We have a lot more to do before getting to that stage. Closing this issue.
