### ISSUE TITLE
Mongo collection standards

### ISSUE THREAD

**Issue by rhomes-wcd** [meteor-gazelle/meteor-gazelle#174]
The Meteor style guide does not include Mongo collection standards. This should be fleshed out moving forward.

**Comment by daveynight** [comment]
According to "Is there a convention to name collection in MongoDb?" on SO[0], the general conventions are:
- lowercase names : avoids case sensitivity issues, MongoDB collection names are case sensitive.
- plural : more obvious to label a collection of something as the plural, e.g. "files" rather than "file"
- no word separators : Avoids issues where different people (incorrectly) separate words (username <-> user_name, first_name <-> firstname). This one is up for debate according to a few people around here but provided the argument is isolated to collection names I don't think it should be ;) If you find yourself improving the readability of your collection name by adding underscores or camelCasing your collection name is probably too long or should use periods as appropriate which is the standard for collection categorization.
- dot notation for higher detail collections : Gives some indication to how collections are related. For example you can be reasonably sure you could delete "users.pagevisits" if you deleted "users", provided the people that designed the schema did a good job ;)

http://stackoverflow.com/a/9868505

As for the third point, I would recommend against including spacers or camel case in collection names, and using the JSON convention, which is camel case, for fields etc.

**Comment by rhomes-wcd** [comment]
Too bad there isnt a more official or widely accepted set of guidelines. I would be inclined to propose the following:
*Collections
-camelCased
-Plural
-No word separators

*Fields
-camelCased
-Plural if array based, otherwise singular
-No word separators.

**Comment by daveynight** [comment]
fwiw I'd be fine with that.

**Comment by rhomes-wcd** [comment]
@ajax-wcd Any thoughts?

**Comment by ghost** [comment]
Fine by me.

**Comment by rhomes-wcd** [comment]
Ill update the readme and submit a PR tonight.

**Comment by jimrollenhagen** [comment]
PR was merged. yay.
