### ISSUE TITLE
Add error routes into router

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#96]
Present users with an error message when accessing urls that don't exist or the user lacks permission for.

**Comment by daveynight** [comment]
One man's low-hanging fruit is another man's stretch, I suppose. 

I spent a few hours fiddling with this and none of the following work'd:
- Implementing according to the instructions here: https://github.com/meteor-useraccounts/iron-routing
- Trying the recommendations on this SO thread: http://stackoverflow.com/questions/28379710/iron-router-not-displaying-notfound-page
- This SO thread also didn't help: http://stackoverflow.com/questions/29906891/using-meteor-useraccounts-core-ensuresignedin-plugin-wont-except-route
- It didn't matter if I made changes and setup routes in `meteor-gazelle-core/lib/router/config.js` or `meteor-gazelle-accounts/lib/accounts.js`

I get the feeling the router config in the core package isn't being read by Meteor at all, but honestly IDK what/where the problem is.  _(ツ)_/

Here's the Gist: https://gist.github.com/daveyshindig/f58fe3878cac9ea6d4da

**Comment by ghost** [comment]
@daveyshindig Thanks for looking into. There's overlap with some of the work I'm doing at the moment with this issue so I'll handle it.

**Comment by daveynight** [comment]
@ajax-wcd Cool, I'm looking forward to seeing how it's fixed. Cheers :)
